# Generated by Django 5.1.4 on 2025-01-20 01:16

import stations.models.station_picture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_description_alter_station_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationpicture',
            name='file',
        ),
        migrations.AddField(
            model_name='stationpicture',
            name='image',
            field=models.ImageField(default='', upload_to=stations.models.station_picture.custom_image_upload_path),
        ),
    ]
