# Generated by Django 5.1.4 on 2025-01-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_remove_stationpicture_file_stationpicture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationpicture',
            old_name='image',
            new_name='picture',
        ),
    ]
