# Generated by Django 5.1.4 on 2025-01-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_rename_image_stationpicture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationpicture',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='picture', serialize=False, to='stations.station'),
        ),
    ]
