# Generated by Django 5.1.4 on 2025-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_stationpicture_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
