# Generated by Django 5.1.4 on 2025-03-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='handle',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
