# Generated by Django 5.1.4 on 2025-03-06 18:35

import stations.models.station_picture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_alter_station_email_alter_station_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationpicture',
            name='picture',
            field=models.ImageField(upload_to=stations.models.station_picture.custom_image_upload_path),
        ),
    ]
