# Generated by Django 5.1.4 on 2025-01-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default='', max_length=44),
        ),
    ]
