# Generated by Django 5.1.4 on 2025-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_pubkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default='', max_length=100),
        ),
    ]
