# Generated by Django 5.1.4 on 2025-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_pubkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=100)),
                ('nonce', models.CharField(blank=True, max_length=36, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
