services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile.app
    volumes:
      - ../app:/usr/src/app
      - ../app/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    volumes:
      - ../api-venv:/usr/src/api
      - media-data:/media
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easybeatz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/certs:/etc/nginx/certs
     - media-data:/media
    depends_on:
      - app
      - api
    networks:
      - app-network

volumes:
  pgdata:
  media-data:

networks: 
  app-network:
    driver: bridge
