# Generated by Django 5.1.4 on 2025-04-11 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
