# Generated by Django 5.1.4 on 2025-04-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_alter_track_bpm_alter_track_tid_alter_track_title'),
        ('carts', '0002_alter_cart_cart_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'track', 'price_model_type'), name='unique_cart_item'),
        ),
    ]
