# Generated by Django 5.1.4 on 2025-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_alter_track_bpm_alter_track_tid_alter_track_title'),
        ('carts', '0003_cartitem_unique_cart_item'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('track', 'price_model_type'), name='unique_cart_item'),
        ),
    ]
