# Generated by Django 5.1.4 on 2025-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
