# Generated by Django 5.1.4 on 2025-01-22 06:21

import albums.models.album_cover
import albums.models.track_mp3
import albums.models.track_wav
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('moods', '0001_initial'),
        ('stations', '0006_alter_stationpicture_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('aid', models.CharField(default='', unique=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('bio', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('genres', models.ManyToManyField(related_name='albums', to='genres.genre')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('tid', models.CharField(default='', unique=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='moods.mood')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumCover',
            fields=[
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cover', serialize=False, to='albums.album')),
                ('picture', models.ImageField(default='', upload_to=albums.models.album_cover.custom_image_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMp3',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mp3', serialize=False, to='albums.track')),
                ('audio', models.FileField(default='', upload_to=albums.models.track_mp3.audio_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackWav',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wav', serialize=False, to='albums.track')),
                ('audio', models.FileField(default='', upload_to=albums.models.track_wav.audio_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
