# Generated by Django 5.1.4 on 2025-01-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
