# Generated by Django 5.1.4 on 2025-01-23 00:05

import albums.models.track_stem
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_track_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackExclusivePrice',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exclusive_price', serialize=False, to='albums.track')),
                ('value', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPrice',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price', serialize=False, to='albums.track')),
                ('value', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='is_exclusive_sold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='TrackStem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('audio', models.FileField(default='', upload_to=albums.models.track_stem.audio_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='albums.track')),
            ],
        ),
    ]
