# Generated by Django 5.1.4 on 2025-01-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_trackexclusiveprice_trackprice_and_more'),
        ('genres', '0002_alter_genre_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='tracks', to='genres.genre'),
        ),
    ]
