# Generated by Django 5.1.4 on 2025-01-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_genres_track_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmp3',
            name='provided_by_eb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackwav',
            name='provided_by_eb',
            field=models.BooleanField(default=False),
        ),
    ]
