# Generated by Django 5.1.4 on 2025-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_trackcollaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
