# Generated by Django 5.1.4 on 2025-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_trackmp3_provided_by_eb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackwav',
            name='provided_by_eb',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
