# Generated by Django 5.1.4 on 2025-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_trackwav_provided_by_eb'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.CharField(default=''),
        ),
    ]
