# Generated by Django 5.1.4 on 2025-02-14 02:41

import albums.models.track_display
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_track_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDisplay',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='display', serialize=False, to='albums.track')),
                ('audio', models.FileField(default='', upload_to=albums.models.track_display.audio_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
