# Generated by Django 5.1.4 on 2025-02-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_trackdisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
