# Generated by Django 5.1.4 on 2025-03-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_trackfavorite'),
        ('stations', '0012_alter_stationpicture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcollaborator',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='stations.station'),
        ),
    ]
