# Generated by Django 5.1.4 on 2025-03-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_alter_trackcollaborator_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
