# Generated by Django 5.1.4 on 2025-03-18 01:48

import albums.models.album_cover
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcover',
            name='picture',
            field=models.ImageField(upload_to=albums.models.album_cover.custom_image_upload_path),
        ),
    ]
