# Generated by Django 5.1.4 on 2025-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_alter_albumcover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='tid',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
