# Generated by Django 5.1.4 on 2025-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_alter_track_bpm_alter_track_tid_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
